<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="MAIN" Id="{4d39b111-49e2-4740-8f14-2e7af4926307}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	heartbeat: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[heartbeat := heartbeat + 1;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>